import { MetadataRoute } from "next";
import { SITE_CONFIG } from "@/lib/constants";

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    { path: "", priority: 1, changeFrequency: "weekly" as const },
    { path: "/services", priority: 0.9, changeFrequency: "monthly" as const },
    { path: "/services/website-development", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/services/startup-mvp-development", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/services/ai-solutions", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/services/full-stack-development", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/website-development-hyderabad", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/btech-major-projects-hyderabad", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/btech-final-year-projects-hyderabad", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/cse-projects-hyderabad", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/ai-ml-projects-hyderabad", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/iot-projects-hyderabad", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/ieee-projects-hyderabad", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/pricing", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/blogs", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/blogs/website-cost-hyderabad-2026", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/blogs/website-vs-instagram-hyderabad", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/blogs/dental-clinic-website-checklist", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/blogs/website-before-google-ads", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/blogs/google-business-profile-website-link", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/blogs/ecommerce-website-cost-india", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/websites-for-businesses", priority: 0.9, changeFrequency: "monthly" as const },
    { path: "/websites-for-dental-clinics", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-doctors", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-restaurants", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-salons", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-real-estate", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-coaching-centres", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-consultants", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-cas", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-small-businesses", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-startups", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/websites-for-portfolios", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/academic-projects", priority: 0.9, changeFrequency: "monthly" as const },
    { path: "/academic-projects/major-projects", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/academic-projects/minor-projects", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/how-it-works", priority: 0.85, changeFrequency: "monthly" as const },
    { path: "/about", priority: 0.8, changeFrequency: "monthly" as const },
    { path: "/start-a-project", priority: 0.95, changeFrequency: "monthly" as const },
    { path: "/demos", priority: 0.7, changeFrequency: "monthly" as const },
    { path: "/demos/dental-clinic", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/dermatologist", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/restaurant", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/salon", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/real-estate-agent", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/ca-firm", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/coaching-centre", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/gym", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/consultant", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/demos/manufacturer", priority: 0.6, changeFrequency: "monthly" as const },
    { path: "/privacy-policy", priority: 0.3, changeFrequency: "yearly" as const },
    { path: "/terms-and-conditions", priority: 0.3, changeFrequency: "yearly" as const },
  ];

  return routes.map(({ path, priority, changeFrequency }) => ({
    url: path ? `${SITE_CONFIG.url}${path}` : `${SITE_CONFIG.url}/`,
    lastModified: new Date(),
    changeFrequency,
    priority,
  }));
}
